- choreograph-addons/choreograph_sale/models/sale_order_line.py
Correction of calculation following change of retribution rate of the base concerned with the addition of the percentage widget, division by 100 is no longer necessary
> [FIX] Calculates the cost of compensation following a change of widget

- .pre-commit-config.yaml
- .prettierrc.yml
- choreograph-addons/choreograph_purchase/__manifest__.py
- choreograph-addons/choreograph_purchase/data/studio_approval_rule.xml
- choreograph-addons/choreograph_sox/data/ir_module_category.xml
- choreograph-addons/choreograph_sox/security/res_groups.xml
[REF]
Correction indentation
[FIX]
Correction precommit pour ne pas prendre en compte le __manifest__ 
Ajout exclusive_user sur l'enregistrement studio.approval.rule
> [REF] [FIX]

- choreograph-addons/choreograph_purchase/__manifest__.py
- choreograph-addons/choreograph_purchase/data/studio_approval_rule.xml
- choreograph-addons/choreograph_purchase/views/purchase_order_views.xml
* [FIX] Ajout attributes studio_approval sur le bouton button_confirm de purchase_order
> Fix/cnxmig 33 (#77)

- choreograph-addons/choreograph_sale/models/sale_order_line.py
- choreograph-addons/choreograph_sale/views/sale_order_views.xml
[FIX]
correction taux de rétribution, rajout taux de rétribution retribution_rate_multi_base dans le calcule pour les multi-bases
> Develop to staging

- choreograph-addons/choreograph_project/models/project_project.py
Surcharge _default_stage_id et _read_group_stage_ids pour prendre le domain project_operation_type
> [FIX] (#144)

- choreograph-addons/choreograph_project/data/project_project_stage.xml
- choreograph-addons/choreograph_project/data/project_task_type.xml
- choreograph-addons/choreograph_project/i18n/fr.po
- choreograph-addons/choreograph_project/models/project_project.py
- choreograph-addons/choreograph_project/models/project_project_stage.py
- choreograph-addons/choreograph_project/models/project_task.py
- choreograph-addons/choreograph_project/models/project_task_type.py
- choreograph-addons/choreograph_project/report/project_report.py
- choreograph-addons/choreograph_project/report/project_report.xml
- choreograph-addons/choreograph_project/views/ir_actions_act_windows.xml
- choreograph-addons/choreograph_project/views/project_project.xml
Reverts Choreograph-Lille/OdooConex#151
> Revert "Develop"

- choreograph-addons/choreograph_contact/__manifest__.py
- choreograph-addons/choreograph_contact/data/res_role.xml
- choreograph-addons/choreograph_sale_project/__manifest__.py
- choreograph-addons/choreograph_sale_project/data/choreograph_project_task_type.xml
- choreograph-addons/choreograph_sale_project/data/project_project.xml
- choreograph-addons/choreograph_sale_project/i18n/fr.po
- choreograph-addons/choreograph_sale_project/models/project_task.py
[IMP] choreograph_contact : ajout res.role
[IMP] choreograph_sale_project : création choreograph_project_task_type et project_project, création de chaque tâche pour chaque projets
> 15.6.3. Initialiser les modèles d'opération et les tâches

- choreograph-addons/choreograph_project/models/project_project.py
- choreograph-addons/choreograph_sale_project/models/project_project.py
- choreograph-addons/choreograph_sale_project/models/project_task.py
Bouton Livrer sur le SO (et sur le projet)	"Ouverture du mail de livraison (ticket 15.11) L'opération passe à l'étape 60-livré"
Quand 90 passe en 15	L'opération passe au statut 80-Extraction Quand 90-Comptage campagnes passe en 80	"L'opération passe en statut 90-Terminé La tâche 95-|Date de dépôt] passe à l'étape 15-A Faire avec Date limite=Date livraison client + 15 jours"
> [FIX] choreograph_project and choreographe_sale_project :

- choreograph-addons/choreograph_sale_project/models/project_project.py
- choreograph-addons/choreograph_sale_project/models/project_task.py
[IMP] choreograph_sale_project: overriding create_project_from_template to update the project with if it's operation type:
- update step
- added task steps
- set default task step
CNXMIG-80
> 15.9.2 Manual generation of transactions

- choreograph-addons/choreograph_sale_project/models/sale_order.py
> [FIX] choreograph_sale_project : add context when open action_view_task

- choreograph-addons/choreograph_sale_project/i18n/fr.po
> Develop to STG : [FIX] choreograph_sale_project : add context when open action_view_task

- choreograph-addons/choreograph_sale_project/models/sale_order.py
- maas-addons/maas_website/views/templates.xml
When the user is not logged in (public user), the href on the button is not set. and if the URL is not defined then the redirection to the language is not done. AND also in the code, data-url_code is not defined. Solution: add t-att-data-url_code="lg[1]"
> Develop to STG : fix/HT00829

- maas-addons/maas_website/views/templates.xml
> [FIX] maas_website : delete address

- maas-addons/maas_website/controllers/main.py
- maas-addons/maas_website/controllers/web.py
- maas-addons/maas_website/views/assets.xml
- maas-addons/maas_website/views/menu.xml
- maas-addons/maas_website/views/templates.xml
> [IMP] maas_website : deactive /operation/indications

- choreograph-addons/choreograph_sale_project/models/project_project.py
- choreograph-addons/choreograph_sale_project/models/project_task.py
when task number 45 in stage 50 > operation got to stage 70
features/HT00849
> [IMP] choreograoh_sale_project

- choreograph-addons/choreograph_project/data/project_task_type.xml
> [IMP] choreogprah_project : change Validation BAT client sequence

- choreograph-addons/choreograph_purchase/__init__.py
- choreograph-addons/choreograph_purchase/i18n/fr.po
- choreograph-addons/choreograph_purchase/models/__init__.py
- choreograph-addons/choreograph_purchase/models/purchase_order.py
features/HT00722
edit :         choreograph-addons/choreograph_purchase/__init__.py
new : choreograph-addons/choreograph_purchase/i18n/fr.po
edit :         choreograph-addons/choreograph_purchase/models/__init__.py
new : choreograph-addons/choreograph_purchase/models/purchase_order.py
> [IMP] choreograph_purchase : change date_approve string to Order Date

- choreograph-addons/choreograph_sale/i18n/fr.po
- choreograph-addons/choreograph_sale/models/sale_order.py
> [IMP] commitment_date required True

- choreograph-addons/choreograph_sale/i18n/fr.po
- choreograph-addons/choreograph_sale/models/sale_order.py
- choreograph-addons/choreograph_sale/views/sale_order_views.xml
- maas-addons/maas_sale_subscription/views/sale_order_view.xml
fix/HT00846
edit  :         choreograph-addons/choreograph_sale/i18n/fr.po
edit :         maas-addons/maas_sale_subscription/views/sale_order_view.xml
> [FIX] commitment_date required if is_subscription = False

- choreograph-addons/choreograph_project/models/project_project.py
- choreograph-addons/choreograph_sale_project/models/project_project.py
- choreograph-addons/choreograph_sale_project/models/sale_order.py
fix/HT00833
edit :         choreograph-addons/choreograph_project/models/project_project.py
edit :         choreograph-addons/choreograph_sale_project/models/project_project.py
> [FIX] fix OP sequence

- choreograph-addons/choreograph_crm/models/__init__.py
- choreograph-addons/choreograph_crm/models/res_partner.py
features/HT00742
edit :         choreograph-addons/choreograph_crm/models/__init__.py
new : choreograph-addons/choreograph_crm/models/res_partner.py
> [IMP] change name_get in crm.lead, kanban view

- choreograph-addons/choreograph_project/models/project_project.py
- choreograph-addons/choreograph_project/views/project_project.xml
- choreograph-addons/choreograph_sale/models/retribution_base.py
- choreograph-addons/choreograph_sale/views/retribution_base_views.xml
- choreograph-addons/choreograph_sale_project/models/project_task.py
- choreograph-addons/choreograph_sale_project/views/project_project.xml
Add code, code_sequence on project.project
Add code on retribution.base
Compute folderkey : project_id.code_sequence,project_id.code,related_base.code,partner_id.ref,sale_order_id.name
features/HT00836
edit :         choreograph-addons/choreograph_project/models/project_project.py
edit :         choreograph-addons/choreograph_project/views/project_project.xml
edit :         choreograph-addons/choreograph_sale/models/retribution_base.py
edit :         choreograph-addons/choreograph_sale/views/retribution_base_views.xml
edit :         choreograph-addons/choreograph_sale_project/models/project_task.py
edit :         choreograph-addons/choreograph_sale_project/views/project_project.xml
> [IMP] Generating the Folder Key

- choreograph-addons/choreograph_sale_project/models/project_project.py
- choreograph-addons/choreograph_sale_project/models/project_task.py
fix/HT00849
edit :         choreograph-addons/choreograph_sale_project/models/project_project.py
edit :         choreograph-addons/choreograph_sale_project/models/project_task.py
> [FIX] uncomment _hook_task_90_in_stage_80

- choreograph-addons/choreograph_project/models/project_project.py
fix/CNXMIG-77
edit :         choreograph-addons/choreograph_project/models/project_project.py
> [FIX] fix delivery assigment

- choreograph-addons/choreograph_project/models/project_project.py
fix/CNXMIG-77
edit :         choreograph-addons/choreograph_project/models/project_project.py
> [FIX] fix delivery assigment (#290)

- choreograph-addons/choreograph_sale_project/models/project_project.py
- choreograph-addons/choreograph_sale_project/models/sale_order.py
When creating the operation:
- redirect to the creation of the corresponding quote
- fill in the customer name, seller, date
features/HT00835
edit :         choreograph-addons/choreograph_sale_project/models/project_project.py
> [IMP] RELEASE 2.0 - GAO - Operation tab in Operation (without order)

- choreograph-addons/choreograph_sale/views/sale_order_views.xml
Only pt1 and pt3
features/HT00878
> [IMP] RELEASE 1.2 - MYMODEL - SUBSCRIPTION

- maas-addons/maas_base/models/mail_message.py
fix/HT00876
edir :         maas-addons/maas_base/models/mail_message.py
> [FIX] sale.operatoin.child > sale.operation.child

- choreograph-addons/choreograph_sale/models/sale_order.py
- choreograph-addons/choreograph_sale/views/sale_order_views.xml
> [FIX] delete pop-up generating operation

- choreograph-addons/choreograph_purchase/i18n/fr.po
- choreograph-addons/choreograph_purchase/views/purchase_order_views.xml
fix/HT00724
edit :         choreograph-addons/choreograph_purchase/i18n/fr.po
edit :         choreograph-addons/choreograph_purchase/views/purchase_order_views.xml
> [i18n] wording

- maas-addons/maas_website/views/templates.xml
fix/HT00925
edit :         maas-addons/maas_website/views/templates.xml
> [FIX] delete hour in column

- maas-addons/maas_website/static/src/js/maas.js
- maas-addons/maas_website/views/templates.xml
fix/HT00924
edit :         maas-addons/maas_website/static/src/js/maas.js
> [FIX] integration of native functionality which was omitted

- choreograph-addons/choreograph_sale/i18n/fr.po
- choreograph-addons/choreograph_sale/views/sale_order_views.xml
> [IMP] make retribution_cost optional

- choreograph-addons/choreograph_sale_project/data/project_project.xml
- choreograph-addons/choreograph_sale_project/models/project_task.py
fix/HT00836
edit :         choreograph-addons/choreograph_sale_project/data/project_project.xml
> [FIX] add code in projet.projet operation template

- choreograph-addons/choreograph_sale/i18n/fr.po
- choreograph-addons/choreograph_sale/models/retribution_base.py
- choreograph-addons/choreograph_sale/models/sale_order_line.py
- choreograph-addons/choreograph_sale/views/retribution_base_views.xml
edit :         choreograph-addons/choreograph_sale/models/retribution_base.py
edit :         choreograph-addons/choreograph_sale/models/sale_order_line.py
edit :         choreograph-addons/choreograph_sale/views/retribution_base_views.xml
> [FIX] fix/HT00934

- maas-addons/maas_website/views/templates.xml
edit :         maas-addons/maas_website/views/templates.xml
> [FIX] fix/HT00949 : change format date to dd/MM/YY

- choreograph-addons/choreograph_contact/i18n/fr.po
- choreograph-addons/choreograph_contact/models/res_partner.py
edit :         choreograph-addons/choreograph_contact/i18n/fr.po
edit :         choreograph-addons/choreograph_contact/models/res_partner.py
> [FIX] fix/HT00688: add tracking on function fields res.partner

- choreograph-addons/choreograph_sale/models/sale_order.py
- choreograph-addons/choreograph_sale/views/sale_order_views.xml
- choreograph-addons/choreograph_sale_project/models/sale_order.py
- choreograph-addons/choreograph_sale_project/views/sale_order.xml
edit :         choreograph-addons/choreograph_sale_project/views/sale_order.xml
> [IMP] features/HT00954 : TODO translation, valided infos

- choreograph-addons/choreograph_sale_project/i18n/fr.po
- choreograph-addons/choreograph_sale_project/models/sale_order.py
- choreograph-addons/choreograph_sale_project/views/sale_order.xml
edit :         choreograph-addons/choreograph_sale_project/i18n/fr.po
edit :         choreograph-addons/choreograph_sale_project/views/sale_order.xml
> [IMP] features/CNXMIG-94

- .gitignore
> [ADD] fix/edit_git_ignore : add .scannerwork/ (Sonarqube scanner)

- choreograph-addons/choreograph_sale/models/sale_order.py
> [FIX] fix/HT00952 : call action_create_task_from_condition when write

- choreograph-addons/choreograph_base/i18n/fr.po
add: choreograph-addons/choreograph_base/i18n/fr.po
> [i18] fix/build_error: add translation

- choreograph-addons/choreograph_project/views/project_task_views.xml
type_of_project field not present in view
edit :         choreograph-addons/choreograph_project/views/project_task_views.xml
> [FIX] fix/HT01057

- choreograph-addons/choreograph_sale_project/models/sale_order.py
For email prospecting, when you check validated info: the email campaign and bat file go into action.
> [FIX] fix/HT01148:

- choreograph-addons/choreograph_sale_project/models/sale_order.py
Correction saving quote following a creation from an operation.
> [FIX] fix/HT00835

- choreograph-addons/choreograph_sale_discount/models/sale_order.py
Fix qty and format currency
edit :         choreograph-addons/choreograph_sale_discount/models/sale_order.py
> [FIX] fix/CNXMIG-106

- choreograph-addons/choreograph_mail/__init__.py
- choreograph-addons/choreograph_mail/__manifest__.py
- choreograph-addons/choreograph_mail/data/mail_followers.xml
- choreograph-addons/choreograph_mail/i18n/fr.po
- choreograph-addons/choreograph_mail/models/__init__.py
- choreograph-addons/choreograph_mail/models/mail_followers.py
- choreograph-addons/choreograph_mail/models/mail_thread.py
- choreograph-addons/choreograph_mail/models/res_company.py
- choreograph-addons/choreograph_mail/models/res_config_settings.py
- choreograph-addons/choreograph_mail/views/res_config_settings.xml
Creation of system settings to disable or not the email subscription feature. Removal of the contact in the suggestion when sending a message.
edit :         choreograph-addons/choreograph_mail/__init__.py
edit :         choreograph-addons/choreograph_mail/__manifest__.py
delete :        choreograph-addons/choreograph_mail/data/mail_followers.xml
new file : choreograph-addons/choreograph_mail/i18n/fr.po
edit :         choreograph-addons/choreograph_mail/models/__init__.py
edit :         choreograph-addons/choreograph_mail/models/mail_followers.py
new file : choreograph-addons/choreograph_mail/models/mail_thread.py
new file : choreograph-addons/choreograph_mail/models/res_company.py
new file : choreograph-addons/choreograph_mail/models/res_config_settings.py
new file : …
> [FIX] fix/HT00851

- choreograph-addons/choreograph_mail/__manifest__.py
Reverts Choreograph-Lille/OdooConex#428
> Revert "[FIX] add choreograph_base"

- choreograph-addons/choreograph_auditlog/report/user_roles_and_right_template.xml
add page-break-after:always; every page on roles and right
> [FIX] fix/CNXMIG-98

- choreograph-addons/choreograph_auditlog/wizards/auditlog_report_wizard.py
get access from group_id.role_ids.model_access_ids
> [FIX] fix/access

- choreograph-addons/choreograph_sale/__manifest__.py
- choreograph-addons/choreograph_sale/data/mail_template_data.xml
- choreograph-addons/choreograph_sale/i18n/fr.po
- choreograph-addons/choreograph_sale/models/sale_order.py
- choreograph-addons/choreograph_sale/report/report_templates.xml
edit :         choreograph-addons/choreograph_sale/__manifest__.py
new file : choreograph-addons/choreograph_sale/data/mail_template_data.xml
new file : choreograph-addons/choreograph_sale/report/report_templates.xml
> [FIX] fix/HT01276

- choreograph-addons/choreograph_sale/__manifest__.py
- choreograph-addons/choreograph_sale/i18n/fr.po
- choreograph-addons/choreograph_sale/report/report_templates.xml
- choreograph-addons/choreograph_sale/report/report_terms_templates.xml
ADD term and conditions
edit :         choreograph-addons/choreograph_sale/__manifest__.py
edit :         choreograph-addons/choreograph_sale/report/report_templates.xml
new file : choreograph-addons/choreograph_sale/report/report_terms_templates.xml
> [IMP] features/CNXMIG-109

- choreograph-addons/choreograph_sale_project/models/sale_order.py
> [FIX] fix/HT01148 : sync data in task 55

- choreograph-addons/choreograph_auditlog/i18n/fr.po
- choreograph-addons/choreograph_auditlog/report/auditlog_report_wizard.xml
- choreograph-addons/choreograph_auditlog/wizards/auditlog_report_wizard.py
- choreograph-addons/choreograph_auditlog/wizards/auditlog_report_wizard.xml
> [IMP] features/HT01311_report : add extracts from suppliers report
